In [1]:
import numpy as np

v = 10
m = 10

## D3 - core pheripheral
## D4 - team of teams

D3 = np.zeros((v, m))
D4 = np.zeros((v, m))

In [18]:

for a3 in np.arange(int(v/2)):
    D3[a3, :]=1

for a4 in np.arange(int(v/2),v):
    D3[a4, a4]=1


for a5 in np.arange(0,v,2):
    D4[a5,a5] = 1
    D4[a5,a5+1] = 1
    D4[a5+1,a5] = 1
    D4[a5+1,a5+1] = 1


In [20]:
print(np.arange(1))

[0]


In [19]:
print(D4)

[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [31]:
def SieveOfEratosthenes(num):
    prime = [True for i in range(num+1)]
    return_string = ''
# boolean array
    p = 2
    while (p * p <= num):
  
        # If prime[p] is not
        # changed, then it is a prime
        if (prime[p] == True):
  
            # Updating all multiples of p
            for i in range(p * p, num+1, p):
                prime[i] = False
        p += 1
  
    # Print all prime numbers
    for p in range(2, num+1):
        if prime[p]:
            return_string = return_string + str(p)
    
    return(return_string)

In [33]:
l1 = SieveOfEratosthenes(20)
l1

'235711131719'

In [34]:
l1[1:5]

'3571'

In [32]:
prime = [True for i in range(20)]

In [27]:
prime 

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]